<?xml version="1.0" ?>
<robot name="reactive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find robot_description)/robot/materials.xacro" />
  <xacro:include filename="$(find robot_description)/robot/properties.xacro" />
  <xacro:include filename="$(find robot_description)/robot/macros.xacro" />
  <xacro:include filename="$(find robot_description)/robot/wheels.xacro" />
  <xacro:include filename="$(find robot_description)/robot/caster_wheels.xacro" />  
  <xacro:include filename="$(find robot_description)/robot/reactive_robot_body.xacro" />
  <xacro:include filename="$(find robot_description)/robot/sensors.xacro" />
  <!-- THIS ORDER IS CRITICAL -->
  <xacro:include filename="$(find robot_description)/robot/reactive_robot_laser_control.xacro" />
  <xacro:include filename="$(find robot_description)/robot/reactive_robot.gazebo" />
  <!-- END -->
  
  


  <xacro:arg name="reactive_robot_name" default="reactive_robot"/>

  <xacro:reactive_robot_body robot_name="$(arg reactive_robot_name)"/>
  
  <xacro:wheel parent="$(arg reactive_robot_name)_chassis" child="$(arg reactive_robot_name)_right_wheel" origin_xyz="0 ${base_box_x / 2.0} ${-1.0 * wheel_radius}" robot_name="$(arg reactive_robot_name)" name_wheel_link="right_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>
  <xacro:wheel parent="$(arg reactive_robot_name)_chassis" child="$(arg reactive_robot_name)_left_wheel" origin_xyz="0 ${-1.0 * base_box_x / 2.0} ${-1.0 * wheel_radius}" robot_name="$(arg reactive_robot_name)" name_wheel_link="left_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>

  <xacro:caster_wheel robot_name="$(arg reactive_robot_name)" parent="$(arg reactive_robot_name)_chassis" caster_wheel_name="front" origin_xyz="${(base_box_x / 2.0) - wheel_increment} 0 ${-1.0* base_box_x / 2.0}" radius="${wheel_increment}" legth="${dummy_length}"/>
  <xacro:caster_wheel robot_name="$(arg reactive_robot_name)" parent="$(arg reactive_robot_name)_chassis" caster_wheel_name="back" origin_xyz="${(-1.0 *base_box_x / 2.0) + wheel_increment} 0 ${-1.0* base_box_x / 2.0}" radius="${wheel_increment}" legth="${dummy_length}"/>
    
  <xacro:reactive_robot_custom_control robot_name="$(arg reactive_robot_name)" parent="$(arg reactive_robot_name)_chassis"/>

  <xacro:reactive_robot_gazebo_systems robot_name="$(arg reactive_robot_name)"/>

  <xacro:laser_scan robot_name="$(arg reactive_robot_name)" parent_name="$(arg reactive_robot_name)_laser_scan_link" origin_xyz="0.0 0.0 ${base_box_x / 2.0}" sensor_YAW="0.0"/>
  <xacro:camera_rgb robot_name="$(arg reactive_robot_name)" parent_name="$(arg reactive_robot_name)_chassis" origin_xyz="${base_box_x/ 1.9} 0.0 ${base_box_x / 2.0}" camera_ROLL="0.0" camera_PITCH="0.0" camera_YAW="0.0"/>
  


</robot>
