<?xml version="1.0" ?>
<robot name="box_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:arg name="box_bot_name" default="box_bot"/>
  <xacro:property name="general_robot_name" value="$(arg box_bot_name)"/>

  <xacro:include filename="$(find box_bot_description)/robot/materials.xacro" />
  
  <xacro:if value="${'boxcleaner' in general_robot_name}">
    <xacro:include filename="$(find box_bot_description)/robot/properties_boxcleaner.xacro" />
    <xacro:include filename="$(find box_bot_description)/robot/box_bot_boxcleaner_brush_control.xacro" />
  </xacro:if>
  <xacro:unless value="${'boxcleaner' in general_robot_name}">
    <xacro:include filename="$(find box_bot_description)/robot/properties.xacro" />
  </xacro:unless>

  <xacro:include filename="$(find box_bot_description)/robot/properties_common.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/macros.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/wheels.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/caster_wheels.xacro" />  
  <xacro:include filename="$(find box_bot_description)/robot/box_bot_body.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/sensors.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/box_bot.gazebo" />




  <xacro:box_bot_body robot_name="$(arg box_bot_name)"/>
 
  <xacro:wheel parent="$(arg box_bot_name)_chassis" child="$(arg box_bot_name)_right_wheel" origin_xyz="0 ${-1.0 * base_box_x / 2.0} ${-1.0 * wheel_radius}" robot_name="$(arg box_bot_name)" name_wheel_link="right_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>
  <xacro:wheel parent="$(arg box_bot_name)_chassis" child="$(arg box_bot_name)_left_wheel" origin_xyz="0 ${base_box_x / 2.0} ${-1.0 * wheel_radius}" robot_name="$(arg box_bot_name)" name_wheel_link="left_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>

  <xacro:caster_wheel robot_name="$(arg box_bot_name)" parent="$(arg box_bot_name)_chassis" caster_wheel_name="front" origin_xyz="${(base_box_x / 2.0) - wheel_increment} 0 ${-1.0* base_box_x / 2.0}" radius="${wheel_increment}" legth="${dummy_length}"/>
  <xacro:caster_wheel robot_name="$(arg box_bot_name)" parent="$(arg box_bot_name)_chassis" caster_wheel_name="back" origin_xyz="${(-1.0 *base_box_x / 2.0) + wheel_increment} 0 ${-1.0* base_box_x / 2.0}" radius="${wheel_increment}" legth="${dummy_length}"/>
    
  <xacro:box_bot_gazebo_systems_slotcar robot_name="$(arg box_bot_name)" name_left_wheel_link="left_wheel" name_right_wheel_link="right_wheel"/>
<!-- 
  <xacro:laser_scan robot_name="$(arg box_bot_name)" parent_name="$(arg box_bot_name)_chassis" origin_xyz="0.0 0.0 ${base_box_x / 2.0}" sensor_YAW="0.0"/>
  <xacro:point_cloud_sensor robot_name="$(arg box_bot_name)" parent_name="$(arg box_bot_name)_chassis" sensor_name="block_laser_scan" origin_xyz="${base_box_x/ 1.9} 0.0 0.0" sensor_YAW="0.0"/>
   -->
  <xacro:camera_rgb robot_name="$(arg box_bot_name)" parent_name="$(arg box_bot_name)_chassis" origin_xyz="${base_box_x/ 1.9} 0.0 ${base_box_x / 2.0}" camera_ROLL="0.0" camera_PITCH="0.0" camera_YAW="0.0"/>
  
<xacro:if value="${'boxcleaner' in general_robot_name}">
    <xacro:box_bot_boxcleaner_brush_control  robot_name="$(arg box_bot_name)" parent="$(arg box_bot_name)_chassis"/>
  </xacro:if>

</robot>
