boxcleaner_2:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz

      velocity_controller:
        type: velocity_controllers/JointGroupVelocityController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  velocity_controller:
    ros__parameters:
      joints:
        - boxcleaner_2_brush_model_link_joint
      interface_name: velocity
      command_interfaces:
        - velocity
      state_interfaces:
        - position
        - velocity
